title: Josh Branchaud
description: a blog about my adventures with and without code

url: http://joshbranchaud.com
permalink: /blog/:categories/:year/:month/:day/:title.html

markdown: kramdown

pygments: true

exclude:
- README.md
- package.json
- node_modules
- Gruntfile.js
- bower.json
- bower_components
